In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import scipy as sc

In [4]:
import sympy as smp

In [5]:
import torch

In [6]:
data = pd.DataFrame({"a" : [1,2,3,4,5],
                    "b" : [6,7,8,9,10],
                    "c" : [11,12,13,14,15],
                    "d" : [16,17,18,19,20],
                    "e" : [21,22,23,24,25],
                    "f" : [26,27,28,29,30],
                    "g" : [31,32,33,34,35],
                    "h" : [36,37,38,39,40]})

In [7]:
p1_defect = np.array([
    [5, 10],
    [5, 1]
])

In [8]:
p1_cooperate = np.array([
    [1, 7],
    [10,7]
])

In [9]:
p2_defect = np.array([1,0])

In [10]:
p2_cooperate = np.array([0,1])

In [11]:
p1_defect.dot(p2_defect)

array([5, 5])

In [12]:
p1_defect.dot(p2_cooperate)

array([10,  1])

In [13]:
p1_cooperate.dot(p2_defect)

array([ 1, 10])

In [14]:
p1_cooperate.dot(p2_cooperate)

array([7, 7])

In [15]:
"""below is matching pennies
    payoffs are:
                 _______________________________
                |(p1,p2)|left   |player2| right |
                |-------|-----------------------|
                |  up   | 3,-3      |   -2,2    |
                |-------|           |           |
                |player1|-----------------------|
                |-------| -1,1      | 0,0       |
                | down  |           |           |
                |_______|___________|___________|
                """

'below is matching pennies\n    payoffs are:\n                 _______________________________\n                |(p1,p2)|left   |player2| right |\n                |-------|-----------------------|\n                |  up   | 3,-3      |   -2,2    |\n                |-------|           |           |\n                |player1|-----------------------|\n                |-------| -1,1      | 0,0       |\n                | down  |           |           |\n                |_______|___________|___________|\n                '

In [16]:
strategy = smp.symbols("sigma_u")
strategy

sigma_u

In [17]:
expect_util_left = smp.Function("EU_l")(strategy)

In [18]:
expect_util_right = smp.Function("EU_R")(strategy)

In [19]:
indifference_equation = smp.Eq(expect_util_left, expect_util_right)
indifference_equation

Eq(EU_l(sigma_u), EU_R(sigma_u))

In [20]:
p2payoff1 = smp.Eq(expect_util_left, -3 * strategy + (1 - strategy) * 1)
p2payoff1

Eq(EU_l(sigma_u), 1 - 4*sigma_u)

In [21]:
p2payoff2 = smp.Eq(expect_util_right, 2 * strategy)
p2payoff2

Eq(EU_R(sigma_u), 2*sigma_u)

In [22]:
indifference_eq = smp.Equality(1 - 4 * strategy, 2 * strategy)
indifference_eq

Eq(1 - 4*sigma_u, 2*sigma_u)

In [23]:
indifference_eq.simplify()

Eq(sigma_u, 1/6)

In [24]:
indifference_eq = smp.Equality(expect_util_left, expect_util_right)
indifference_eq

Eq(EU_l(sigma_u), EU_R(sigma_u))

In [31]:
lagrangian = smp.Function("l")(expect_util_left, expect_util_right)

In [32]:
indif_lagra = smp.Equality(lagrangian, expect_util_left - expect_util_right)
indif_lagra

Eq(l(EU_l(sigma_u), EU_R(sigma_u)), -EU_R(sigma_u) + EU_l(sigma_u))

In [34]:
indif_lagra_der = smp.Equality(lagrangian.diff(strategy), (expect_util_left - expect_util_right).diff())
indif_lagra_der

Eq(Derivative(EU_R(sigma_u), sigma_u)*Derivative(l(EU_l(sigma_u), EU_R(sigma_u)), EU_R(sigma_u)) + Derivative(EU_l(sigma_u), sigma_u)*Derivative(l(EU_l(sigma_u), EU_R(sigma_u)), EU_l(sigma_u)), -Derivative(EU_R(sigma_u), sigma_u) + Derivative(EU_l(sigma_u), sigma_u))