In [1]:
import numpy as np
import sympy as smp
import torch as tc
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

In [2]:
class Test_Neural_Net(nn.Module):
    def __init__(self, terms):
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(terms, 55),
            nn.ReLu()
        )

In [5]:
data = np.array ([
    [12, 20, 20, 30],
    [11, 9, 40, 50],
    [12, 26, 18, 10]
])

In [8]:
for entry in data:
    print (entry)

[12 20 20 30]
[11  9 40 50]
[12 26 18 10]


In [10]:
len(data)

3

In [11]:
len(data) - 1

2

In [12]:
data[1]

array([11,  9, 40, 50])

In [14]:
for index in range(len(data)):
    print (index)

0
1
2


In [ ]:
|